# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20171217_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.User'),
            preserve_default=False,
        ),
    ]
